### ISSUE TITLE
cuda.cudart.cudaRuntimeGetVersion() hard-codes the runtime version, rather than querying the runtime

### ISSUE THREAD

**Issue by bdice** [NVIDIA/cuda-python#16]
The current implementation of `cuda.cudart.cudaRuntimeGetVersion()` hard-codes the runtime version, rather than querying the runtime for its version. This results in incorrect runtime versions if the runtime version is different from the version of cuda-python.

https://github.com/NVIDIA/cuda-python/blob/746b773c91e1ede708fe9a584b8cdb1c0f32b51d/cuda/_lib/ccudart/ccudart.pyx#L79-L82

https://github.com/NVIDIA/cuda-python/blob/746b773c91e1ede708fe9a584b8cdb1c0f32b51d/cuda/_lib/ccudart/utils.pyx#L37

### Additional context

A workaround used in https://github.com/rapidsai/rmm/pull/946 is to use numba's API for this instead:

```python
import numba.cuda

def cudaRuntimeGetVersion():
    major, minor = numba.cuda.runtime.get_version()
    return major * 1000 + minor * 10
```

**Comment by jakirkham** [comment]
cc @vzhurba01

**Comment by kmaehashi** [comment]
This is a good finding, @bdice! This issue also impacts CuPy, as it heavily relies on `cudaRuntimeGetVersion` to test the availability of features.
https://github.com/cupy/cupy/blob/514457a58b34baa386ace365b997e49698bf36d3/cupy_backends/cuda/libs/nvrtc.pyx#L83-L84

**Comment by vzhurba01** [comment]
Thanks @bdice! Sorry for the late response, for now this is a known limitation of CUDA Python which first requires a fix in the CUDA Runtime library. Let me explain...

Problem: The CUDA Runtime library has a race-condition on Windows with regards to the DLL unload order resulting in a crash. This was reported to happen often enough to be a very frustrating experience for users, so CUDA Python needed to find an alternative.

Solution: What CUDA Python does today is it actually re-writes the CUDA Runtime library as seen in [cuda/_lib/ccudart](https://github.com/NVIDIA/cuda-python/tree/main/cuda/_lib/ccudart). While it does contain some simplification, it is functionally equivalent to the latest CUDA Runtime release. This avoids loading the CUDA Runtime library, avoiding the race-condition.

Next Step: Once this race-condition is resolved in the CUDA library, we'll switch to loading and calling into the library (just like CUDA Driver and NVRTC) and remove the rewritten CUDA Runtime. Since the rewritten Runtime is functionally equivalent, there should be no noticeable change once this transition is complete. I know that the work for this race-condition has been scheduled, but I don't know when it's expected to be resolved.

How this relates to the `cudaRuntimeGetVersion`, it's value will always be the latest toolkit because the rewritten Runtime will always be up-to-date. In the meantime I'm really sorry for the awkwardness this has caused.

**Comment by bdice** [comment]
Thanks @vzhurba01! Do you know if this behavior would cause any other unexpected behavior besides the version? We may need workarounds for other functions if so. I am not familiar enough with the API surface area to think of any off the top of my head, but it seems possible.

**Comment by vzhurba01** [comment]
I've just scanned through the APIs and nothing else stood out to me. I think this is a one-off case because it uses a global value as defined by the library.

But I should also mention this: The usage of `cuda.cudart.CUDART_VERSION` is not the same as C users and might cause confusion.

`cuda.cudart.CUDART_VERSION` is for CUDA Python
`cuda.cudart.cudaRuntimeGetVersion()` is for CUDA Runtime library

All other APIs appear to simply format parameters between Runtime and Driver, then call into driver. While the logic of APIs would be different between older Runtime vs. latest Runtime, this shouldn't be a concern because of backwards comparability.

**Comment by bdice** [comment]
@vzhurba01 Following up on this. Is it _still_ impossible to get the true runtime version with `cuda-python`? We face this issue repeatedly in RMM, Numba, cuDF, cupy, and other libraries. It's a serious need to address for pretty much all Python packages that are using CUDA. For example, I see in the comment above that cupy is querying the nvrtc version as a proxy for the cudart version. We're currently struggling here in `cudf` because we cannot import `numba` and use its runtime version logic due to other constraints: https://github.com/rapidsai/cudf/pull/13337#discussion_r1200937520

I know there's been some changes since mid-2022 in how cuda-python works (e.g. `ccudart.pxd` was changed to `ccudart.pxd.in` and there's some logic that reads the actual runtime headers, as I understand it). I wondered if any of those changes might have improved the situation here.

**Comment by leofang** [comment]
Revisiting this issue a little more than a year later, I come with a different viewpoint than I had before.

First of all, thanks to @vzhurba01 this issue is worked around for Linux users in CUDA Python 12.3. A new API `cudart.getLocalRuntimeVersion()` is added to probe the local `libcudart.so` version. (btw @vzhurba01, this API is currently undocumented -- it does not appear in the API reference.)

Second, based on [Vlad's description on the (old) status quo](https://github.com/NVIDIA/cuda-python/issues/16#issuecomment-1018880404), one can think of cudart as being statically linked to CUDA Python (which allows users to interact to the statically linked cudart from Python). Then, it is perfectly valid that an API like `cudaRuntimeGetVersion()` returns the version used at build time, since for CUDA Python users the local `libcudart` version is irrelevant. 

I think the "new" status quo (having both `cudaRuntimeGetVersion()` for build-time version and `getLocalRuntimeVersion()` for "run-time"[^1] version) is a perfect balance. Other CUDA libraries also start offering the former.

[^1]: Quotation added because whether or not this version is useful/relevant is context dependent. For Numba etc, it is. But not so much for pure CUDA Python users.

**Comment by vzhurba01** [comment]
With the CUDA Python 12.3.0 release, as @leofang mentioned we now have `getLocalRuntimeVersion()` to help probe the local `libcudart.so`.
Missing the API reference is now fixed, though description remains similar to `cudaRuntimeGetVersion()`).

With these two APIs available, looks like this issue is ready to be closed!
