### ISSUE TITLE
Can't get attribute for CU_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED

### ISSUE THREAD

**Issue by apowers313** [NVIDIA/cuda-python#184]
When I call `cuDeviceGetAttribute` with `cuda.CUdevice_attribute.CU_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED` I get the error `<CUresult.CUDA_ERROR_INVALID_VALUE: 1>`.

Seems like it might be an off-by-one error since it's the last value in the Enum `CUdevice_attribute`?

[Here is some code](https://gist.github.com/apowers313/3f85e410705c1e65aa7a3e94e263f48a) to reproduce the problem.

**Comment by leofang** [comment]
What's your CUDA Python version and driver version?
-  CUDA Python version can be accessed via either `python -c "from cuda import __version__; print(__version__)"` (but this will change later, see https://github.com/NVIDIA/cuda-python/issues/75), `pip list | grep cuda` if you installed it via pip, or `conda list cuda-python` if via conda.
- Driver version is reported by `nvidia-smi` (we just need the "CUDA Version" here)

**Comment by apowers313** [comment]
CUDA Python: 12.6.0
CUDA Driver: 12.4

**Comment by leofang** [comment]
This happens because the driver support for `CU_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED` was added since CUDA 12.5, so to use it you need to update both your CUDA driver and CUDA sw (in this case, cuda-python) to >=12.5.

I am not sure why this is not mentioned in the CUDA Release Notes, but the way I checked this is to search `CU_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED` in the driver API docs, which are versioned so that you can search the same term by jumping across different minor versions. The first time this enumerator appeared was CUDA 12.5.0.

btw what's your use case of CIG? Do you have some graphics rendering pipeline written in Python?

**Comment by apowers313** [comment]
Use case was iterating all the enums to print out all the device capabilities to the screen.

Thanks for the help.
